/**
 * Lista oficial de marcas rastreadas pelo bot.
 * Usada como termo de busca nos collectors e para filtrar produtos por marca.
 */

export const BRANDS: string[] = [
  "Amend",
  "Aura Beauty",
  "Bauny",
  "Belas Garden",
  "Bioderma",
  "Bioré",
  "Blant",
  "BM Beauty",
  "Boca Rosa",
  "Braé",
  "Bruna Tavares",
  "CARE",
  "Carolina Herrera",
  "Catharine Hill",
  "Catrice",
  "CeraVe",
  "Clarins",
  "Clinique",
  "Contém1g",
  "Creamy",
  "Dailus",
  "Dapop",
  "Darrow",
  "Dior",
  "Dove",
  "Dudah!",
  "Essence",
  "Estée Lauder",
  "Eucerin",
  "Eudora",
  "Fenzza",
  "Fran by Franciny Ehlke",
  "Garnier",
  "Giorgio Armani",
  "Giovanna Baby",
  "Givenchy",
  "Granado",
  "Guerlain",
  "Hada Labo",
  "Head & Shoulders",
  "Hits",
  "Impala",
  "Inoar",
  "Isdin",
  "Kamaleão Color",
  "Kérastase",
  "Kiko Milano",
  "Klasme",
  "La Roche-Posay",
  "Lancôme",
  "Lola From Rio",
  "L'Oréal Paris",
  "L'Oréal Professionnel",
  "LP Beauty",
  "Luisance",
  "MAC",
  "Macrilan",
  "Mahav",
  "Make B.",
  "Makiê",
  "Mari Maria",
  "Mascavo",
  "Maybelline",
  "Melano CC",
  "Melu",
  "Mia Make",
  "Miss Frandy",
  "Miss Lary",
  "Missha",
  "Natura",
  "Neutrogena",
  "Niina Secrets",
  "Nina Makeup",
  "Nivea",
  "Nouf",
  "O Boticário",
  "Océane",
  "OPI",
  "Pam by Pamella",
  "Pantene",
  "Payot",
  "Petrizi",
  "Phállebeauty",
  "Pink21",
  "Principia",
  "Quem Disse, Berenice?",
  "Rabanne",
  "Real Techniques",
  "Redken",
  "Revlon",
  "Ricca",
  "Risqué",
  "Rom&nd",
  "Ruby Kisses",
  "Ruby Rose",
  "Sallve",
  "Salon Line",
  "Sebastian",
  "Shiseido",
  "Sisley",
  "Skelt",
  "Skinceuticals",
  "Taiff",
  "Tangle Teezer",
  "Too Faced",
  "Truss",
  "Vichy",
  "Vizzela",
  "Vult",
  "Wella",
  "Widi Care",
];

/**
 * Versão normalizada (lowercase, sem marcadores especiais) para matching em texto.
 */
export const BRAND_KEYWORDS_NORMALIZED: string[] = BRANDS.map(b =>
  b.toLowerCase().replace(/[?!.]/g, "").trim()
);